project:
  type: website
  output-dir: docs

website:
  title: "esther-amores.github.io"
  navbar:
    search: true
    left:
      - file: index.qmd
        text: Home
      - about.qmd
    favicon: images/logo.png

format:
  html:
    theme: 
      light: minty
      dark: darkly
    css: styles.css
    toc: true

editor: visual

